# Generated by Django 2.2.3 on 2022-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blkchainapproach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=100)),
                ('docid', models.IntegerField()),
                ('patientname', models.CharField(max_length=100)),
                ('patientid', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('sysmptid', models.IntegerField()),
                ('ledgerbalance', models.FloatField()),
                ('tranxid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transactionsstore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docid', models.IntegerField()),
                ('patientid', models.IntegerField()),
                ('nameoncard', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
                ('cardnumber', models.CharField(max_length=100)),
                ('expiredate', models.CharField(max_length=100)),
                ('tranxid', models.IntegerField()),
                ('price', models.FloatField()),
                ('ledgerbalance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='patientsymptomsanalysis',
            name='docname',
            field=models.CharField(default='notassigned', max_length=600),
        ),
        migrations.AddField(
            model_name='patientsymptomsanalysis',
            name='status',
            field=models.CharField(default='waiting', max_length=600),
        ),
        migrations.AlterField(
            model_name='patientsymptomsanalysis',
            name='createdon',
            field=models.DateTimeField(max_length=50),
        ),
    ]
