# Generated by Django 2.2.3 on 2022-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorreplaysysmptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=10)),
                ('sysid', models.CharField(max_length=100)),
                ('patinetname', models.CharField(max_length=60)),
                ('docid', models.CharField(max_length=60)),
                ('doctorname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=600)),
                ('mobile', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=600)),
                ('patinetallsymptoms', models.CharField(max_length=5000)),
                ('diseasname', models.CharField(max_length=600)),
                ('descriptions', models.CharField(max_length=600)),
                ('reqdate', models.DateTimeField()),
                ('prescription1', models.CharField(max_length=100)),
                ('prescription2', models.CharField(max_length=100)),
                ('prescription3', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('blkchMoney', models.CharField(max_length=100)),
                ('respdate', models.DateTimeField()),
                ('status', models.CharField(max_length=600)),
            ],
        ),
    ]
